PACKAGE_VERSION=$(shell cat ../../VERSION)
CFLAGS=-g -Wall -std=gnu99 -DPACKAGE_VERSION=\"$(PACKAGE_VERSION)\" `pkg-config --cflags gtk+-2.0` -I../..
LDFLAGS=-L../../plugins -lgolplug `pkg-config --libs gtk+-2.0 gmodule-2.0` -lshell32 -lsqlite3 -lcrypto -lws2_32 -lcurl

all : libmsagent.dll

libmsagent.dll : msagent.o
	gcc -shared -g -o libmsagent.dll msagent.o $(LDFLAGS) -lole32 -loleaut32 -luuid

msagent.o : msagent.c display_msagent.xpm
	gcc -g -Wall -c $(CFLAGS) -o msagent.o msagent.c

clean:
	-rm *.o *.res *.exe *.dll
