PACKAGE_VERSION=$(shell cat ../../VERSION)
CFLAGS=-g -Wall -std=gnu99 -DPACKAGE_VERSION=\"$(PACKAGE_VERSION)\" `pkg-config --cflags gtk+-2.0` -I../..
LDFLAGS=-L../../plugins -lgolplug `pkg-config --libs gtk+-2.0 gmodule-2.0` -lshell32 -lsqlite3 -lcrypto -lws2_32 -lcurl

all : libballoon.dll

libballoon.dll : balloon.o
	gcc -shared -g -o libballoon.dll balloon.o $(LDFLAGS)

balloon.o : balloon.c display_balloon.xpm
	gcc -g -Wall -c $(CFLAGS) -o balloon.o balloon.c

clean:
	-rm *.o *.res *.exe
